name: bye_bye_cry_new
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  perfect_volume_control: ^1.0.5
  flutter_riverpod: ^2.1.3
  audioplayers: ^2.0.0
  firebase_auth: ^4.2.5
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.17
  flutter_screen_wake: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add asset to your application, add an asset section, like this:
  assets:
    - asset/images/
    - asset/images/icon_png/
    - asset/images/sounds_image/
    - asset/images/icon_png/now_playing_icon/
    - assets/babyCry/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding asset from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Neue Einstellung
      fonts:
        - asset: asset/fonts/NeueEinstellung-Normal.otf
        - asset: asset/fonts/Neue Einstellung Bold.ttf
        - asset: asset/fonts/f0174917-35f6-45fd-bd28-21254c0a6102.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
